### ISSUE TITLE
FITUR MIGRASI | MIGRATION FEATURE

### ISSUE THREAD

**Issue by Auful01** [1ets/lets-go-framework#1]
Fitur ini dibuat untuk memudahkan pengguna framework ini agar menjadi mudah ketika membuat sebuah tabel dan kolomnya
----------
<i>The Feature made for framework user for easly when create new tables and columns </i>

**Comment by dhutapratama** [comment]
Feel free to create your own contribution by pushing to the forked repository and then create a pull request

aniway, if its running, it will moved to console project like artisan on laravel
